[primary.links]
".zshrc" = "~/.zshrc"
".xonshrc" = "~/.xonshrc"

[device.macbook2021]
platform = "mac"
links = {
    "macbook-config.zsh" = "~/.config.zsh"
}

[device.macbook2021.links]
"macbook-2021.sh" = "~/.config.zsh"
platform = "mac"

[platform.mac.links]
# TODO
