# Configuration for my 2017 Arch Linux Lenovo Laptop

browser = "/usr/bin/firefox"

# My custom path
# ~/.zshrc handles '~' expansion
# 
# NOTE: These are prepended *AFTER* the system bin (for security reasons)
path = [
    "~/.yarn/bin",
    "~/.cargo/bin",
    "~/go/bin",
    # My private bin ($HOME/bin) 
    "~/bin",
    # Where pip puts its bin files
    "~/.local/bin",
    # TODO: I really don't like hardcoding these
    "~/.gem/ruby/2.5.0/bin",
    "~/.rustup/nightly-x86_64-unknown-linux-gnu/bin/",
]

[prompt.xonsh]
# NOTE: Prefix with 'py' to indicate we are in xonsh
# We really should be prefixing with 'xonsh', but 'py' is shorter
# It's not really ambiguous, since this is really the python-prompt (for all
# intents and purposes)
# I'm not going to confuse with the regular python interpreter (python3) cause i'll
# know its a shell
prefix = "py"
prefix_color = "yellow"
