# This config is semi-secret, meaning it is private (but unencrypted)
#
# **WARNING**: This is unencrypted, so should not contain passwords/keys

[usernames]

# Example: bitwarden = "larry.page@gmail.com"
bitwarden = { ty:wq, example = "larry.page@gmail.com" }
