#!/usr/bin/env fish
if test (count $argv) -lt 1
    echo "ERROR: Expected at least one argument" >&2
    echo "Usage: check_line_length <file_name>+" >&2
    return 1
end

for file_name in $argv
    if test ! -f $file_name
        echo "ERROR: File not found: $file_name" >&2
        return 1
    end
end

for file_name in $argv
    echo -n "$file_name: "
    # Need to keep count to work around empty files
    set -l line_count 0
    for line in (cat $file_name)
        echo (string length $line)
        set line_count (math "$line_count + 1")
    end | sort -n | tail -1
    # Check for empty file
    if test $line_count = 0
        echo "0"
    end
end
