#!/usr/bin/env python3
"""Generates random ASCII text."""

import argparse
import random


def srange(x: str, y: str) -> list[str]:
    """All characters in the inclusive range from x to y"""
    xi, yi = ord(x), ord(y)
    assert xi <= yi
    return [chr(c) for c in range(xi, yi + 1)]


_DESCRIPTION: str | None = __doc__.splitlines()[0] if __doc__ else None
ASCII_NUMS = srange("0", "9")
ASCII_ALPHA = srange("a", "z") + srange("A", "Z")
ASCII_ALPHANUM = ASCII_ALPHA + ASCII_NUMS


def rand_ascii(length: int, /, *, rand: random.Random | None = None) -> str:
    if rand is None:
        rand = random.Random()
    assert length >= 0
    letters = rand.choices(ASCII_ALPHANUM, k=length)
    return "".join(letters)


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="randascii",
        description=_DESCRIPTION,
    )
    parser.add_argument(
        "--length",
        "-l",
        help="The length of the string to generate",
        type=int,
        required=True,
    )

    args = parser.parse_args()
    assert args.length >= 0, "The --length cannot be negative"

    print(rand_ascii(args.length))


if __name__ == "__main__":
    main()
