#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
diff-editor = ":builtin"
diff-formatter = ":git"
show-cryptographic-signatures = false
default-command = "log"
pager = "moor --quit-if-one-screen --no-linenumbers --terminal-fg"

[user]
name = "Techcable"
email = "git@techcable.net"

[git]
# fetch all remotes by default
fetch = "*"

[signing]
backend = "gpg"
behavior = "own"

[[--scope]]
--when.hostname = ["archlinux-lenovo-2017"]

# change signing behavior from on archtop because gpg requires frequent passphrase prompts
# Using `keep` causes more prompts than `drop` would,
# but makes it less likely to strip a signature added by another machine
# This difference should only come up when doing forced pushes or transferring changes outside git
[--scope.signing]
behavior = "keep"

[--scope.git]
sign-on-push = true

[aliases]
stat = ["show", "--stat"]
# Run `jj split` but with reverse preservation of change ids.
# In both cases, the selected changes are placed in the first commit.
#
# By default jj split on `xy` means the first commit with theselected changes has change id `xy`,
# while the second commit is given a new change id.
# This does the reverse, the selected changes have the new change id and are still placed first
splitr = ["split", "-B", "@"]
rsplit = ["splitr"]

[fsmonitor]
# This is not enabled globally because on macOS
# it means each repo needs several seconds to startup
# backend = "watchman"
